<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQr0rove\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQr0rove/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQr0rove.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQr0rove\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQr0rove\appDevDebugProjectContainer([
    'container.build_hash' => 'Qr0rove',
    'container.build_id' => '4b0e80b1',
    'container.build_time' => 1555929163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQr0rove');
