<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\SOSController:SOSInscription' => function () {
    return ${($_ = isset($this->services['service_locator.p2tjb5k']) ? $this->services['service_locator.p2tjb5k'] : $this->load('getServiceLocator_P2tjb5kService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SOSController:SOSLogin' => function () {
    return ${($_ = isset($this->services['service_locator.k59hlbf']) ? $this->services['service_locator.k59hlbf'] : $this->load('getServiceLocator_K59hlbfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SOSController::SOSInscription' => function () {
    return ${($_ = isset($this->services['service_locator.p2tjb5k']) ? $this->services['service_locator.p2tjb5k'] : $this->load('getServiceLocator_P2tjb5kService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\SOSController::SOSLogin' => function () {
    return ${($_ = isset($this->services['service_locator.k59hlbf']) ? $this->services['service_locator.k59hlbf'] : $this->load('getServiceLocator_K59hlbfService.php')) && false ?: '_'};
}]));
