<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5mo3ahe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5mo3ahe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5mo3ahe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5mo3ahe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5mo3ahe\appDevDebugProjectContainer([
    'container.build_hash' => '5mo3ahe',
    'container.build_id' => 'ce6cbd5a',
    'container.build_time' => 1555889515,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5mo3ahe');
