<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwsxncj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwsxncj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRwsxncj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRwsxncj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRwsxncj\appDevDebugProjectContainer([
    'container.build_hash' => 'Rwsxncj',
    'container.build_id' => '968bd2b8',
    'container.build_time' => 1555800502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwsxncj');
